apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.crons.markForDeletionScheduler.name }}
spec:
  schedule: "{{ .Values.crons.markForDeletionScheduler.cron }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Values.crons.markForDeletionScheduler.name }}
            image: radial/busyboxplus:curl
            env:
            - name: SECURITY_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: security-credentials
                  key: security-user
            - name: SECURITY_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: security-credentials
                  key: security-password
            - name: DELETE_TARGET
              value: {{ .Values.crons.markForDeletionScheduler.del_target }}
            - name: MARK_FOR_DELETE_TARGET
              value: {{ .Values.crons.markForDeletionScheduler.mark_for_del_target }}
            args:
            - /bin/sh
            - -c
            - curl -u $(SECURITY_USER_NAME):$(SECURITY_USER_PASSWORD) -X DELETE http://$(AUTH_SERVICE_HOST):$(AUTH_SERVICE_PORT)/$(DELETE_TARGET)
            - curl -u $(SECURITY_USER_NAME):$(SECURITY_USER_PASSWORD) -X DELETE http://$(AUTH_SERVICE_HOST):$(AUTH_SERVICE_PORT)/$(MARK_FOR_DELETE_TARGET)
          restartPolicy: OnFailure
