language: python
sudo: required
dist: trusty
python: '3.6'

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - make lint
  - pipenv run pytest --cov=ras_rm_auth_service --cov-report xml
  - pipenv run coverage report

after_success:
  - pipenv run codecov

branches:
  only:
    - master
