# Generated by Django 2.0.6 on 2018-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='alternative_hash',
            field=models.TextField(help_text='Passlib based hash. ', null=True, verbose_name='alternative_hash'),
        ),
    ]
