env: minikube

replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  requests:
    memory: "256Mi"

dns:
  enabled: false
  wellKnownPort: 8080

crons:
  deleteUsersScheduler:
    name: auth-delete-users-scheduled-job
    cron: "0 0 * * *"
    target: "/api/batch/account/users"
  markUsersForDeletionScheduler:
    name: auth-mark-users-for-deletion-scheduled-job
    cron: "0 1 * * *"
    target: "/api/batch/account/users/mark-for-deletion"
  dueDeletionThirdNotificationScheduler:
    name: auth-third-deletion-notification-scheduled-job
    cron: "0 2 * * *"
    target: "/api/batch/account/users/third-notification"
  dueDeletionSecondNotificationScheduler:
    name: auth-second-deletion-notification-scheduled-job
    cron: "0 3 * * *"
    target: "/api/batch/account/users/second-notification"
  dueDeletionFirstNotificationScheduler:
    name: auth-first-deletion-notification-scheduled-job
    cron: "0 4 * * *"
    target: "/api/batch/account/users/first-notification"

notify:
  dueDeletionFirstNotificationTemplate: due_deletion_first_notification_templates
  dueDeletionSecondNotificationTemplate: due_deletion_second_notification_templates
  dueDeletionThirdNotificationTemplate: due_deletion_third_notification_templates

sendEmailToGovNotify: true

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test
