env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

# Application cpu limit is set quite high as bcrypt verification takes longer when it's not set high enough
resources:
  application:
    requests:
      cpu: "100m"
      memory: "200Mi"
    limits:
      cpu: "700m"
      memory: "300Mi"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "10m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 125
  cpuPercentage: 200
replicas: 1
maxReplicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

dns:
  enabled: false
  wellKnownPort: 8080

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test

developmentConfig: true
