env: minikube

image:
  devRepo: eu.gcr.io/ons-rasrmbs-management
  name: eu.gcr.io/ons-rasrmbs-management
  tag: latest
  pullPolicy: Always

database:
  managedPostgres: false
  sqlProxyEnabled: false
  secrets:
    usernameKey: username
    passwordKey: password
    nameKey: db-name

container:
  port: 8080
service:
  port: 8080

resources:
  application:
    requests:
      memory: "200Mi"
      cpu: "35m"
    limits:
      memory: "500Mi"
      cpu: "500m"
  proxy:
    requests:
      memory: "25Mi"
      cpu: "5m"
    limits:
      memory: "64Mi"
      cpu: "100m"

autoscaling: false
scaleAt:
  # These are expressed as a percentage of resources.requests, not resources.limits
  memoryPercentage: 125
  cpuPercentage: 200
replicas: 1
rollingUpdate:
  maxSurge: 1
  maxUnavailable: 1

dns:
  enabled: false
  wellKnownPort: 8080

crons:
  deleteUsersScheduler:
    name: auth-delete-users-scheduled-job
    cron: "0 0 * * *"
    target: "/api/batch/account/users"
  markUsersForDeletionScheduler:
    name: auth-mark-users-for-deletion-scheduled-job
    cron: "0 1 * * *"
    target: "/api/batch/account/users/mark-for-deletion"
  dueDeletionNotificationScheduler:
    name: auth-due-deletion-notification-scheduled-job
    cron: "0 2 * * *"
    image: auth-scheduler

notify:
  dueDeletionFirstNotificationTemplate: due_deletion_first_notification_templates
  dueDeletionSecondNotificationTemplate: due_deletion_second_notification_templates
  dueDeletionThirdNotificationTemplate: due_deletion_third_notification_templates

sendEmailToGovNotify: true

gcp:
  project: ras-rm-sandbox
  topic: ras-rm-notify-test